### ISSUE TITLE
Circle Meeting 2 - CA and T&M Meeting - Tuesday August 3rd at 14.00 UTC 

### ISSUE THREAD

**Issue by stephen-rowan** [Catalyst-Swarm/Catalyst-Circle-Co-ordination#14]
### Tuesday August 3rd at 14.00 UTC  ([Source](https://docs.google.com/document/d/1ADPgUiznBeMO9hluJbPWUCophBg2uKnrzBK-DA-LTyY/edit))

Call Victor & Felix

#### Agenda items for 
- CC meeting https://github.com/Catalyst-Swarm/Catalyst-Circle-Co-ordination/issues/13 ( Victors suggestions )
- [x] 1 hour discuss problem gathered statements
- [x] 1/2 hour discuss voting process for CCv2
- [x] 1/2 CC potentially evolution
- [x] Expectation/Objectives and Roadmap for the next 4 meetings

#### Action Items besides CC meetings ( common suggestions )
- [x]  Recruiting ghostwriter/ notetaker:
- Peter Oliver - Krueger
- Tevo Saks
- [x]  Setting up a dev team to develop a circle-tool 
- Lucio Baglione
- Aharon
- Stephen Whitenstall
- [x] Enable resources to pay dev for developing the circle-tool.
- IOG&CF
