### ISSUE TITLE
Circle Meeting 1 - Toolmaker and Maintainer Circle - Tracking

### ISSUE THREAD

**Issue by stephen-rowan** [Catalyst-Swarm/Catalyst-Circle-Co-ordination#3]
# Circle Meeting 1 - Toolmaker and Maintainer Circle - Tracking

## The Catalyst Alliance Meeting - 17/07/2021 - 16:00

- [x] @FelixfromSwarm - The Catalyst Alliance Meeting - 17/07/2021 - 16:00

## 1) Saturday Swarm Session - 17/07/2021 - 18:00

- [x] @FelixfromSwarm - Saturday Swarm Session - 17/07/2021 - 18:00

![2021-07-19](https://user-images.githubusercontent.com/25156451/126143116-193afe50-aa07-452d-a52c-b41c872b6925.png)

### Discord context
https://discord.com/channels/756943420660121600/864481683621543947/866618990242955264

### Recording from Saturday T&M problem sensing
https://drive.google.com/file/d/1g8DnVHvrIQ_ZyFmEU0C-7lJKQQLNcuY7/view?usp=sharing

### Miro Board link
https://miro.com/app/board/o9J_l6MT8rY=/?moveToWidget=3074457361524586504&cot=14

## 2) After Town Hall - Wednesday, 21st, July 2021
- [x] @FelixfromSwarm - After Townhall - 21/07/2021 - 20:00
https://catalyst-swarm.gitbook.io/catalyst-circle/toolmakers-and-maintainers/activity#t-and-m-problem-sensing-2

![2021-07-21 (4)](https://user-images.githubusercontent.com/25156451/126639551-f08aca0f-d532-4b08-bebd-620736439eb7.png)

## 3) Saturday Swarm Session - 24th July 2021
- [x] @FelixfromSwarm - Saturday Swarm Session - 24/07/2021 - 18:00
https://catalyst-swarm.gitbook.io/catalyst-circle/toolmakers-and-maintainers/activity#t-and-m-problem-sensing-3

![2021-07-29 (7)](https://user-images.githubusercontent.com/25156451/127469104-7cf87ccb-0dc4-4baf-ab1c-ed0eb3013c82.png)

## 4) After Town Hall, 28th July 2021 - Final Form of T&M Problem Statement
- [x] @FelixfromSwarm - After Town Hall, 28th July 2021 - 24/07/2021 - 20:00

https://catalyst-swarm.gitbook.io/catalyst-circle/toolmakers-and-maintainers/activity#t-and-m-problem-sensing-4

![2021-07-29 (8)](https://user-images.githubusercontent.com/25156451/127470159-f3fa0bc2-24a6-4eb7-82d4-bdf733c77414.png)
